modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/mariot7/XL-Food-Mod/issues"
[[mods]]
modId="xlfoodmod"
version="2.0.2"
displayName="XL Food Mod"
updateJSONURL="https://raw.githubusercontent.com/mariot7/XL-Food-Mod/1.14/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/xl-food-mod"
logoFile="logo.png"
credits="SoBiohazardous, Igrek, geogeooo59"
authors="mariot7"
description='''
A mod that adds more foods and crops to the game.
'''

[[dependencies.xlfoodmod]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xlfoodmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"